### ISSUE TITLE
test error on win10 eclipse

### ISSUE THREAD

**Issue by jview** [jcuda/jcuda-samples#2]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error while loading native library "JCublas2-0.8.0-windows-x86_64"
Operating system name: Windows 10
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: C:\Users\chenjh\AppData\Local\Temp\JCublas2-0.8.0-windows-x86_64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
	at jcuda.jcublas.JCublas2.initialize(JCublas2.java:81)
	at jcuda.jcublas.JCublas2.<clinit>(JCublas2.java:66)
	at jcuda.runtime.samples.JCudaRuntimeMappedMemory.main(JCudaRuntimeMappedMemory.java:48)
Stack trace from the attempt to load the library as a resource:
java.lang.UnsatisfiedLinkError: C:\Users\chenjh\AppData\Local\Temp\JCublas2-0.8.0-windows-x86_64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:260)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:158)
	at jcuda.jcublas.JCublas2.initialize(JCublas2.java:81)
	at jcuda.jcublas.JCublas2.<clinit>(JCublas2.java:66)
	at jcuda.runtime.samples.JCudaRuntimeMappedMemory.main(JCudaRuntimeMappedMemory.java:48)
---(end of nested stack traces)---

	at jcuda.LibUtils.loadLibrary(LibUtils.java:193)
	at jcuda.jcublas.JCublas2.initialize(JCublas2.java:81)
	at jcuda.jcublas.JCublas2.<clinit>(JCublas2.java:66)
	at jcuda.runtime.samples.JCudaRuntimeMappedMemory.main(JCudaRuntimeMappedMemory.java:48)

**Comment by jview** [comment]
The dll file exist on  folder path:

C:\Users\chenjh\AppData\Local\Temp>dir |findstr JC*
2017/09/02  15:54           165,548 +JXF2759345464086579225.tmp
2017/09/02  17:32           246,784 JCublas-0.8.0-windows-x86_64.dll
2017/09/02  17:30           487,424 JCublas2-0.8.0-windows-x86_64.dll
2017/09/02  17:27           237,056 JCudaDriver-0.8.0-windows-x86_64.dll
2017/09/02  17:27           401,408 JCudaRuntime-0.8.0-windows-x86_64.dll
2017/09/02  17:52           272,384 JCudnn-0.8.0-windows-x86_64.dll
2017/09/02  17:52           217,088 JNvgraph-0.8.0-windows-x86_64.dll

**Comment by jcuda** [comment]
The part of the message that says

> Can't find dependent libraries

usually means that the CUBLAS DLL is not found on the system. 

Did you install the NVIDIA CUDA SDK? (And, which version of it did you install?)

**Comment by jview** [comment]
Thant's for help,I upgrade driver and install CUDA sdk from https://developer.nvidia.com/cuda-downloads

It's ok now.
